### ISSUE TITLE
-bash: lapis_lazuli: command not found

### ISSUE THREAD

**Issue by dabudeveloper** [spriteCloud/lapis-lazuli#105]
I am trying to follow the instructions in regard to start a project. I followed the mac instructions (http://www.testautomation.info/Installing_ruby_with_cucumber_on_a_mac_machine).

However trying to create a folder the command line
(so in terminal navigate to the (new) project path) with lapis_lazuli create foldername 
i am getting -bash: lapis_lazuli: command not found

i also tried to do it from the lapis lazuli folder with the complete pathname after create but still the same. 

Any ideas what I am doing wrong?

**Comment by sjieg** [comment]
Are you able to execute ruby commands from that folder? Like `irb` or `ruby -v`

When installing the `lapis_lazuli` gem, a file is added to the ruby installation folder: `./Ruby23/bin/lapis_lazuli`
In general the Ruby/bin folder should have been added to your PATH and thus all files in there are globally available.

If the file is not in the /bin/ folder, then something must have gone wrong during LL installation.
If `ruby -v` doesn't work either from the project path, then something must have gone wrong with the Ruby installation.

**Comment by dabudeveloper** [comment]
having dropped lapis_lazuli file into the terminal and then executed the create command, worked. So i believe that my PATH is not correct then.
