### ISSUE TITLE
Find solution for chrome issue with "element not clickable"

### ISSUE THREAD

**Issue by jfinkhaeuser** [spriteCloud/lapis-lazuli#20]
If we can find a solution to circumventing this issue, TA engineer's lives would be much easier.

https://code.google.com/p/selenium/issues/detail?id=2766

---

In the **\* case, all instances of this were solved by scrolling the element into view. That means we don't need to spend any time on this right now unless it crops up again in future.

**Comment by sjieg** [comment]
TODO: Investigate if this issue is still present in the current versions of selenium and chromedrive.
Selenium actually closed the issue on their side, but it seems they just used a workaround instead of fixing it.

**Comment by barzilay** [comment]
Not reproducible anymore. Closing issue.
