### ISSUE TITLE
Emulate screenshot taking on OS X

### ISSUE THREAD

**Issue by jfinkhaeuser** [spriteCloud/lapis-lazuli#22]
Problem:

```
undefined method `save_screenshot' for #<Selenium::WebDriver::Driver:0x007f976c71add0> (NoMethodError)
```

Potential solution:

``` bash
$ screencapture file_name.png
```

**Comment by osteenbergen** [comment]
Is this running locally on OSX or via Selenium Grid? Does this affect the Firefox driver or Safari?

**Comment by jfinkhaeuser** [comment]
Locally on OS X, and really for anything.

We had some issues on older OS X workers, and this approach looked like it could get us around them.

**Comment by barzilay** [comment]
Closing. Obsolete.
