### ISSUE TITLE
Don't bail out if a project did not include other dependencies

### ISSUE THREAD

**Issue by jfinkhaeuser** [spriteCloud/lapis-lazuli#23]
Hidden dependencies of this type are:

- `selenium-webdriver`
- `watir-webdriver`

All that should happen when they're missing is for browser-related functionality to be unavailable.

**Comment by jfinkhaeuser** [comment]
Relates to #29 - might want to close this.

**Comment by barzilay** [comment]
#29 is merged. Closing this issue.
