### ISSUE TITLE
Clarification Multi_find(_all)

### ISSUE THREAD

**Issue by sjieg** [spriteCloud/lapis-lazuli#37]
**Note:** I might misinterpreted the documentation, so please explain if I'm wrong.

We need to clarify the use of Multi in de finding methods. In the documentation it's described that Multi_find() should be:
- Find an element matching :selector1 OR :selector2
  When using find() it should be:
- Find an element matching :selector1 AND :selector2

How it currently is working:

``` Ruby
browser.goto 'google.com'
#Elm on page: <input id="lst-ib" class="gsfi" />

# :selector1 OR :selector2 method
browser.find(
  {:input => {:class => "gsfi"}}, 
  {:input => {:id=> "X"}}
).flash
# Input element flashes, the above is seen as an OR statement

# :selector1 AND :selector2 method
browser.find(
  :input => {:class => "gsfi"},
  :input => {:id=> "gsfi"}
).flash
# Input element flashes, both selectors apply to the input field.

# :selector1 AND :selector2 method
browser.find(
  :input => {:class => "gsfi"},
  :input => {:id=> "X"}
).flash
# Error appears because no element is found with both class="gsfi" AND id="X"
```

In the above example it doesn't matter whether you use `multi_find()` or just `find()`. Also the same applies when using `multi_find_all()` or `find_all()`, except that it finds an array of 3 elements when using the OR method.

From my point of view we should update the documentation and make `multi` obsolete, removing it completely from the documentation.

Else we would have to update the code that `multi` will make any way multiple selectors are given is seen as an OR statement and without `multi` should always be seen as an AND statement.

**Comment by sjieg** [comment]
I've figured this one out. The following it the solution:

**find A or B**
``` Ruby
# Will check if either one is present
browser.multi_find(
  {:like => [:a, :text, 'A']},
  {:like => [:a, :text, 'B']}
).flash
```
**Find element containing A and B**
``` Ruby
browser.find(
  :a => {
    :class => 'A', 
    :text => 'B'
  }
).flash
```

Unfortunately it's not possible to use `:like` when you're looking for an element with and A and B

Testing this did bring up a new issue with `multi_find_all()`, but I'll create a new ticket for that.

**Comment by jfinkhaeuser** [comment]
The difference between `find` and `multi_find` is indeed that you can provide multiple selectors and they use AND or OR logic.

Note that in your example, you're implicitly switching between a single and multiple selectors:

```ruby
browser.find(
  {:input => {:class => "gsfi"}}, 
  {:input => {:id=> "X"}}
).flash
```

The first `{}` is the first argument, the second `{}` the second argument. After (find.rb:183)[https://github.com/spriteCloud/lapis-lazuli/blob/master/lib/lapis_lazuli/browser/find.rb#L183], you should have them both in the `:selectors` key in the options, with the rest of the options reverted to defaults.

Having two selectors is what makes this OR logic.

(Note I'm saying this half from memory, half from skimming code - I might be wrong. It's been a while.)

By contrast:
```ruby
browser.find(
  :input => {:class => "gsfi"},
  :input => {:id=> "gsfi"}
).flash
```

Here you're passing a *single* selector that happens to have two values to it. That turns it into AND logic.

You can also do this explicitly by passing the `:selectors` key (an Array), containing either one or two values.

**Comment by jfinkhaeuser** [comment]
The difference between `*find` and `*find_all` is indeed that the latter returns an Array of all matches. If you have two elements matching the same AND logic, or two elements each matching parts of OR'd selectors, it should make a difference.

**Comment by jfinkhaeuser** [comment]
Lastly, the differences between the different functions are (or should be):

- `find` will find the first match for any of the selectors
- `find_all` will find all matches for any of the selectors
- `multi_find` will find the first match for all of the selectors
- `multi_find_all` will find all matches for all of the selectors

Now taking my explanation about selectors above into account, it's true that `find` with a single selector and `multi_find` with a single selector should do exactly the same.

**Comment by jfinkhaeuser** [comment]
Note: for *find*, the distinction above may not be super important. For *wait* (which is based on *find*), the distinction makes a difference between how often you run a query, and therefore performance.

Again, all this from memory and skimming code, there might be bugs in my logic, too.

**Comment by sjieg** [comment]
Thanks @jfinkhaeuser 

In my first comment when creating the tickets I made many mistakes, for example:
``` Ruby
  :input => {:class => "gsfi"},
  :input => {:id=> "gsfi"}
```
Is that both selectors start with `:input`, and is overwritten by itself:
```
(irb):293: warning: key :input is duplicated and overwritten on line 294
```


From my research it seems that adding these 2 have the same behavior:
``` Ruby
browser.multi_find(
  {selector1},
  {selector2}
)
browser.multi_find(
  :selectors => [
    {selector1}, 
    {selector2}
  ]
)
```

All in all, I've figured how to do an AND & OR statement now, so therefor the ticket is done.
