### ISSUE TITLE
When running LL in IRB: SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by sjieg** [spriteCloud/lapis-lazuli#38]
## Devices
- Windows 10 & Windows 7
- Ruby 2.0 & Ruby 2.3

## Description
1) Open CMD (makes sure it's a fresh CMD start)
2) Start irb
``` Ruby
require 'lapis_lazuli'
include LapisLazuli
browser.goto 'google.com'
```
## Actual

An error appears:
``` Ruby
SystemStackError: stack level too deep
        from C:/Ruby200/lib/ruby/2.0.0/irb/workspace.rb:86
Maybe IRB bug!
```
In Ruby 2.3 a bit more information is given. See: https://www.dropbox.com/s/d437ek3eypispnm/Screenshot%202016-08-11%2015.12.25.png?dl=0

## Expected

The browser to open and got to google.com

## Note

This only happens if the first thing you do after starting CMD is going to IRB. If you run a Cucumber script first and then open IRB, everything works fine.

I've already pinpointed the problem being somewhere in loading the Config, where it can't find the config,yml file and keeps going trough a loop to find it, instead of giving a message that no config was found.

**Comment by barzilay** [comment]
Hmm interesting. The world/config module is initialized over and over again. Will need more investigation.

**Comment by osteenbergen** [comment]
Its likely the logging module, as it needs configuration for its setup.

The config module should have a check to determine if its loaded or not.
Then the logging module can write to stdout during initialisation.

If i have some time left i will write the pull request.

Onno

**Comment by barzilay** [comment]
Thanks for the feedback Onno. We'll investigate further as well, but a pull request is always welcome.

**Comment by sjieg** [comment]
Found the source of the problem:
`load_config_from_file(filename) #config.rb:138`
Catches any error thrown when failing to find the config file it is loading.

`load_config(config_name) #config.rb:82`
Rescues any error thrown by `load_config_from_file` and does nothing with the error.

`init #config.rb:41`
calls `load_config` if `@config` is still nil. After doing this, it will store the browser `@metadata`, in which `log.debug` is called.

`log #logging.rb:27`
Will use the method `env_or_config('log_dir')`, which is a method in `config.rb` and thus will trigger `init #config:41`.

So while `@config` is nil, it will keep trying to load it infinitely. Causing the SystemStackError.

I think the following code could fix it:
Old:
``` Ruby
#config.rb:51 (init)
load_config(Config.config_file)
```

New:
```
#config.rb:51 (init)
load_config(Config.config_file)
if @config.nil?
  warn 'Unable to find a configuration file, defaulting to empty config.yml'
  @config = {}
end
```
@osteenbergen any feedback on this solution?

**Comment by jfinkhaeuser** [comment]
Kind of makes sense, but only kind of. The `logging.rb` functionality should fail gracefully when `env_or_config('log_dir')` returns nothing.lib/lapis_lazuli/world/logging.rb#L32

I think [logging.rb:32](lib/lapis_lazuli/world/logging.rb#L32) is the issue, i.e. that it tries to use the directory name without checking whether it's nil.

**Comment by sjieg** [comment]
@jfinkhaeuser I `believe env_or_config('log_dir')` should never fail because `log_dir` has a default value in options.rb:23. However, this value is never reached because it keeps trying to look for a config file that doesn't exist.
