### ISSUE TITLE
Lapis Lazuli should throw custom errors

### ISSUE THREAD

**Issue by sjieg** [spriteCloud/lapis-lazuli#53]
At the moment when LL throw an error, 9 out of 10 times it's a default RuntimeError. We should change this into custom errors, for example:

- LapisLazuli::TimeoutError
- LapisLazuli::ElementNotFoundError
- LapisLazuli::WaitError
- LapisLazuli::FindError

This will allow users to rescue a specific error, instead of catching all errors and then later on, figure out they have been catching a critical error, costing them more time to fix.

**Comment by barzilay** [comment]
Closing. Errors are caught and passed to watir. Will remain that way.
