### ISSUE TITLE
Wiki out-of-date?

### ISSUE THREAD

**Issue by osteenbergen** [spriteCloud/lapis-lazuli#7]
Some parts of the Wiki, like find examples, haven't changed since the first version I wrote. Probably will contains stuff that no longer works

**Comment by osteenbergen** [comment]
* Add metadata features to the wiki

**Comment by jfinkhaeuser** [comment]
Good comment from 8 days ago, I just thought the same. Let me add it :)

**Comment by jfinkhaeuser** [comment]
Added https://github.com/spriteCloud/lapis-lazuli/wiki/WorldModule::Config#metadata

**Comment by jfinkhaeuser** [comment]
Added https://github.com/spriteCloud/lapis-lazuli/wiki/Software-Version-Handling#persistence

**Comment by barzilay** [comment]
Onging but these sources describe most of the features and usage:

http://www.testautomation.info/Welcome

http://www.rubydoc.info/gems/lapis_lazuli/LapisLazuli
