### ISSUE TITLE
RFC: Add touch gestures to LL

### ISSUE THREAD

**Issue by mark0203** [spriteCloud/lapis-lazuli#80]
Since LL is already supporting selenium-grid out of the box, it would be really handy if LL would also support touch gestures. That way websites that expect a touch gesture on elements (instead of a click), will than be testable as well.

The appium_lib supports touch actions: http://www.rubydoc.info/github/appium/ruby_lib/Appium/TouchAction
But that requires me to rewrite all tests with the appium driver.
I did notice that in Appium it did not work out of the box, you also needed to switch to the NATIVE_APP context, see discussion on the appium forum: https://discuss.appium.io/t/ruby-appium-touchaction-perform-returns-error-method-has-not-yet-been-implemented/18308

```ruby
browser.set_context("NATIVE_APP")
tap_action = Appium::TouchAction.new.tap(element: e, x:0.5, y:0.5)
tap_action.perform
```

Another alternative that works with LL is to make use of the browser.execute_script(<some_js_code>)
There was a gem that was said to work with watir-webdriver called touch_action (version 1.3.3), but it is outdated and I can't get it to work, see: https://github.com/Ricardonacif/touch_action/issues/10

So as a workaround I could use the browser.execute_script(<some_javascript_code_here>) to perform the touch. Touch events require something like 'touchstart' & 'touchend'
The script below is what I created for now for the element I need to tap

```ruby
elm_array = browser.wait_all(:like => [:div, :class, 'row ng-scope'])
loop_index = 0
elm_array.each do
  elm = browser.find(:like => [:div, :text, 'sometext'], :context => elm_array[loop_index], :throw => false)
  if elm
    row_index = loop_index
	puts "match found in row #{row_index + 1}"
  end
  loop_index += 1
end

browser.execute_script("s = $('.mp-listcontrol-control').first().controller().scope; s._dblclickRow('#{row_index}', { type: 'touchend', target: { localName: '', hasClass: function() { return false; }  } }); s.$apply()")
```

But it would be awesome if I could just do something like: 

```ruby
elm = browser.find(:like => [:div, :class, 'someclassname'])
elm.tap
elm.swipe
```

**Comment by mark0203** [comment]
Just something I realized.
The tap I'm excecuting with the execute_script right now is not the same as a touch gesture from appium_lib. It's only triggering the javascript touchstart/touchend to pretend there was a click.

**Comment by sjieg** [comment]
I'm afraid this will not be picked up by us, because of 2 reasons:
- Most mobile websites support click actions to be read out as tap actions
- We rely on Watir to do any browser interaction and we try not to customize that part too much. LL is mainly a helper for the selection of elements.

**Comment by jfinkhaeuser** [comment]
@mark0203 You can try out https://github.com/jfinkhaeuser/unobtainium, or https://github.com/jfinkhaeuser/unobtainium-cucumber for a little more comfort.

Unobtainium has a driver extension mechanism https://github.com/jfinkhaeuser/unobtainium/blob/master/docs/DRIVER_MODULES.md which would allow you to add the required functionality in an add-on gem fairly simply.

**Comment by mark0203** [comment]
@jfinkhaeuser That sounds interesting. I did see this extend function a couple of times, but I'm not familiar with how to use it yet. Most likely it's easy to use when you know how to use it. Anyway I'll pass this information on to our dev. At some point we might needs some simular trick for swipe actions and than this might come in handy.
