### ISSUE TITLE
browserName capability required in order to start the Edge browser via the grid

### ISSUE THREAD

**Issue by mark0203** [spriteCloud/lapis-lazuli#85]
**My setup:**

- Watir 6.8.4
- Selenium-webdriver 3.6.0
- Selenium-Standalone-Server 3.6.0

Since Watir 6.6 they changed the way to call for a remote browser and capabilities.
(see release notes: http://watir.com/watir-6-6/)
However for Edge there seems to be an issue and I need to enter an additional capability to make it work.

**In Watir this works:**
```ruby
require 'watir'
url = "http://localhost:4444/wd/hub" 
Watir::Browser.new :edge, {url: url, platform: "WIN10"}
```

**In LapisLazuli this fails:**
```ruby
require 'lapis_lazuli'
include LapisLazuli
url = "http://localhost:4444/wd/hub" 
browser :edge, {url: url, platform: "WIN10"}

```
**Workaround that seems to work for now (add the browserName capability):**
```ruby
browser :edge, {url: url, platform: "WIN10", browserName: "MicrosoftEdge"}
```
The issue is only related to the Edge browser. 
FF and Chrome work fine without the need for the additional browserName capability.
So these both work fine:
```ruby
browser :firefox, {url: grid-url, platform: "WIN10"} 
browser :chrome, {url: grid-url, platform: "WIN10"} 
```

**Comment by sjieg** [comment]
The issue is probably located in:
https://github.com/spriteCloud/lapis-lazuli/blob/master/lib/lapis_lazuli/browser.rb
Between line 283 and 413, where optional_data is somehow overwritten.

Possibly caused by the code that's allowing Device Simulation.

**Comment by mark0203** [comment]
fixed by now.
